# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-03 02:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20)),
                ('birthdate', models.DateField()),
                ('avatar', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='upload_location', width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('digitalid', models.CharField(max_length=20)),
                ('ultimateupdate', models.DateTimeField()),
                ('inicio_cargo', models.DateField(auto_now=True)),
                ('años_exp', models.IntegerField(blank=True, null=True)),
                ('contrato', models.TextField(blank=True, null=True)),
                ('legales_asoc', models.TextField(blank=True, null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Cargo')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Especialidad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ultimateupdate'],
            },
        ),
    ]
