# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-09 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20170821_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Especialidad'),
        ),
    ]
