# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-09 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20171009_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Cargo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rut',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
