# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-25 17:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0011_auto_20171011_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil_Obrero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
                ('apellido', models.TextField(max_length=100)),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('birthdate', models.DateField()),
                ('avatar', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='upload_location', width_field='width_field')),
                ('height_field', models.IntegerField(blank=True, default=0, null=True)),
                ('width_field', models.IntegerField(blank=True, default=0, null=True)),
                ('digitalid', models.CharField(blank=True, max_length=20, null=True)),
                ('ultimateupdate', models.DateTimeField()),
                ('cargo', models.TextField(default='Obrero', max_length=20)),
                ('comite_par', models.BooleanField(default=False)),
                ('inicio_cargo', models.DateField(auto_now=True)),
                ('años_exp', models.IntegerField(blank=True, null=True)),
                ('contrato', models.FileField(blank=True, null=True, upload_to='')),
                ('legales_asoc', models.FileField(blank=True, null=True, upload_to='')),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Especialidad')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor2', to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Unidad')),
            ],
            options={
                'ordering': ['-ultimateupdate'],
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='supervisor',
        ),
    ]
