# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-25 20:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20171025_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_obrero',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor2', to=settings.AUTH_USER_MODEL),
        ),
    ]
