# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-28 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20171028_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='perfil_obrero',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Especialidad_staff'),
        ),
    ]
