# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-12 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activitys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='asunto',
            new_name='module',
        ),
    ]
