# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-28 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
