# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-20 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0003_auto_20170920_1415'),
        ('activitys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='carpeta',
            field=models.ManyToManyField(related_name='carpetas', to='modulos.Carpeta'),
        ),
        migrations.AddField(
            model_name='activity',
            name='estado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
