# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-12 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0003_remove_carpeta_user_asign'),
        ('activitys', '0002_auto_20170912_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='module',
        ),
        migrations.AddField(
            model_name='activity',
            name='carpeta',
            field=models.ManyToManyField(to='modulos.Carpeta'),
        ),
    ]
