# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-20 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0003_auto_20170920_1415'),
        ('activitys', '0002_auto_20170920_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='carpeta',
        ),
        migrations.AddField(
            model_name='activity',
            name='table_records',
            field=models.ManyToManyField(related_name='carpetas', to='modulos.Carpeta'),
        ),
    ]
