# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-12 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activitys', '0003_auto_20170912_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='slug',
        ),
    ]
