# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-20 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activitys', '0003_auto_20170920_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='table_records',
            new_name='carpeta',
        ),
    ]
