# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-16 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
