# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-16 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170815_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dotacion_max',
            field=models.IntegerField(default=0),
        ),
    ]
