# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-21 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170821_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='fecha_inicio',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='fecha_termino',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
