# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-21 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20170821_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
