# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-13 22:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='')),
                ('fecha_up', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, default='Faltante', max_length=20, null=True)),
                ('archivo', models.ManyToManyField(blank=True, null=True, to='modules.Archivo')),
                ('asign_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Modular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('porcent', models.IntegerField(default=0)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submodulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('porcent', models.IntegerField(default=0)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('carpetas', models.ManyToManyField(to='modules.Carpeta')),
            ],
        ),
        migrations.AddField(
            model_name='modulo',
            name='submodulo',
            field=models.ManyToManyField(to='modules.Submodulo'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='user_prev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modular',
            name='modules',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Modulo'),
        ),
    ]
