# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-07 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_profile_number'),
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100)),
                ('porcent', models.IntegerField(default=0)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('user_asign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable1', to='profiles.Profile')),
            ],
            options={
                'db_table': 'carpeta',
            },
        ),
        migrations.DeleteModel(
            name='Music',
        ),
    ]
