# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-07 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_auto_20171107_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.TextField()),
                ('singer', models.TextField()),
                ('last_modify_date', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'music',
            },
        ),
        migrations.RemoveField(
            model_name='carpeta',
            name='user_asign',
        ),
        migrations.DeleteModel(
            name='Carpeta',
        ),
    ]
