# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-07 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0003_auto_20171107_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='song',
            new_name='nombre',
        ),
    ]
