# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-07 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_profile_number'),
        ('musics', '0004_auto_20171107_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='singer',
        ),
        migrations.AddField(
            model_name='music',
            name='user_asign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable1', to='profiles.Profile'),
        ),
    ]
