# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-13 23:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submodulo',
            name='carpetas',
            field=models.ManyToManyField(related_name='carpeta', to='modulos.Carpeta'),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='user_asign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to=settings.AUTH_USER_MODEL),
        ),
    ]
