# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-12 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpeta',
            name='estado',
            field=models.CharField(blank=True, default='Faltante', max_length=20, null=True),
        ),
    ]
