# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-12 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_auto_20170912_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpeta',
            name='user_asign',
        ),
    ]
