# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-13 23:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modulos', '0002_auto_20170913_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_termino', models.DateTimeField(blank=True, null=True)),
                ('porcent', models.IntegerField(default=0)),
                ('estado', models.CharField(max_length=20)),
                ('user_asign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='carpeta',
            name='user_asign',
        ),
        migrations.AlterField(
            model_name='submodulo',
            name='carpetas',
            field=models.ManyToManyField(related_name='carpeta', to='modulos.Carpetas'),
        ),
        migrations.DeleteModel(
            name='Carpeta',
        ),
    ]
