# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-07 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_modular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modular',
            old_name='models',
            new_name='modules',
        ),
    ]
