# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-28 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0004_auto_20170928_0945'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proceso',
            new_name='SubCarpeta',
        ),
        migrations.RemoveField(
            model_name='submodulo',
            name='proceso',
        ),
        migrations.AddField(
            model_name='carpeta',
            name='subcarpeta',
            field=models.ManyToManyField(blank=True, null=True, related_name='subcarpeta', to='modulos.SubCarpeta'),
        ),
    ]
