# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-28 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0011_auto_20170928_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpeta',
            name='is_subcarpeta',
        ),
    ]
