# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-29 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0016_auto_20170928_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejecucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='subcarpeta',
            name='cumplimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to='modulos.Ejecucion'),
        ),
    ]
