# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-01 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0017_auto_20170929_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('update', models.DateField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='')),
            ],
        ),
    ]
