# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-01 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0020_auto_20170930_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='tipo',
        ),
        migrations.AddField(
            model_name='template',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documento', to='modulos.Documento'),
        ),
    ]
