# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-01 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0021_auto_20170930_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='documento',
        ),
        migrations.AddField(
            model_name='documento',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template', to='modulos.Template'),
        ),
    ]
