# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-01 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0022_auto_20170930_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='depto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='titulo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
