# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-01 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0024_auto_20171001_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
