# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-01 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0026_auto_20171001_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='subtitulo1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='subtitulo2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='titulo',
            field=models.TextField(default='Titulo'),
            preserve_default=False,
        ),
    ]
