# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-23 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0027_auto_20171001_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='user1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='profiles.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documento',
            name='user2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='profiles.Profile'),
            preserve_default=False,
        ),
    ]
