# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-30 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0030_documento_firmas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpeta',
            name='subcarpeta',
            field=models.ManyToManyField(blank=True, related_name='subcarpeta', to='modulos.SubCarpeta'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='firmas',
            field=models.ManyToManyField(blank=True, to='profiles.Profile'),
        ),
    ]
