# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-31 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0031_auto_20171030_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='etapa',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
