# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-31 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0032_documento_etapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
