# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-01 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import modulos.models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0033_documento_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='fecha2',
            field=models.DateField(blank=True, default=modulos.models.get_deadline, null=True),
        ),
    ]
