# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-01 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20171028_1323'),
        ('modulos', '0035_documento_fecha3'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='firmasobr',
            field=models.ManyToManyField(blank=True, to='profiles.Perfil_Obrero'),
        ),
    ]
