# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-02 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0037_documento_suma_firmas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='suma_firmas',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
