# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-02 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0039_auto_20171101_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='suma_firmas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
