# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-03 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0042_carpeta_cumplimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='submodulo',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_carpeta1', to='modulos.Tipo'),
        ),
    ]
