# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-05 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0043_submodulo_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpeta',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='carpeta',
            name='fecha_termino',
        ),
        migrations.RemoveField(
            model_name='carpeta',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='carpeta',
            name='user_asign',
        ),
        migrations.RemoveField(
            model_name='subcarpeta',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='subcarpeta',
            name='fecha_termino',
        ),
        migrations.RemoveField(
            model_name='subcarpeta',
            name='user_asign',
        ),
    ]
