# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-05 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0044_auto_20171105_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpeta',
            name='submodulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub2', to='modulos.Submodulo'),
        ),
    ]
